//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace DirectorioInteractivo.DirectorioWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectorioServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DirectorioService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearEdificioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearNivelOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearLocalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearTipoLocalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DirectorioService() {
            this.Url = global::DirectorioInteractivo.Properties.Settings.Default.DirectorioInteractivo_DirectorioWebService_DirectorioService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CrearUsuarioCompletedEventHandler CrearUsuarioCompleted;
        
        /// <remarks/>
        public event CrearEdificioCompletedEventHandler CrearEdificioCompleted;
        
        /// <remarks/>
        public event CrearNivelCompletedEventHandler CrearNivelCompleted;
        
        /// <remarks/>
        public event CrearLocalCompletedEventHandler CrearLocalCompleted;
        
        /// <remarks/>
        public event CrearTipoLocalCompletedEventHandler CrearTipoLocalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearUsuario(string nombre_usuario, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string email, string password) {
            this.Invoke("CrearUsuario", new object[] {
                        nombre_usuario,
                        primer_nombre,
                        segundo_nombre,
                        primer_apellido,
                        segundo_apellido,
                        email,
                        password});
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string nombre_usuario, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string email, string password) {
            this.CrearUsuarioAsync(nombre_usuario, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, email, password, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string nombre_usuario, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string email, string password, object userState) {
            if ((this.CrearUsuarioOperationCompleted == null)) {
                this.CrearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsuario", new object[] {
                        nombre_usuario,
                        primer_nombre,
                        segundo_nombre,
                        primer_apellido,
                        segundo_apellido,
                        email,
                        password}, this.CrearUsuarioOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioOperationCompleted(object arg) {
            if ((this.CrearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearEdificio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearEdificio(string nombre, string descripcion) {
            this.Invoke("CrearEdificio", new object[] {
                        nombre,
                        descripcion});
        }
        
        /// <remarks/>
        public void CrearEdificioAsync(string nombre, string descripcion) {
            this.CrearEdificioAsync(nombre, descripcion, null);
        }
        
        /// <remarks/>
        public void CrearEdificioAsync(string nombre, string descripcion, object userState) {
            if ((this.CrearEdificioOperationCompleted == null)) {
                this.CrearEdificioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEdificioOperationCompleted);
            }
            this.InvokeAsync("CrearEdificio", new object[] {
                        nombre,
                        descripcion}, this.CrearEdificioOperationCompleted, userState);
        }
        
        private void OnCrearEdificioOperationCompleted(object arg) {
            if ((this.CrearEdificioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEdificioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearNivel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearNivel(int numero, string descripcion) {
            this.Invoke("CrearNivel", new object[] {
                        numero,
                        descripcion});
        }
        
        /// <remarks/>
        public void CrearNivelAsync(int numero, string descripcion) {
            this.CrearNivelAsync(numero, descripcion, null);
        }
        
        /// <remarks/>
        public void CrearNivelAsync(int numero, string descripcion, object userState) {
            if ((this.CrearNivelOperationCompleted == null)) {
                this.CrearNivelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearNivelOperationCompleted);
            }
            this.InvokeAsync("CrearNivel", new object[] {
                        numero,
                        descripcion}, this.CrearNivelOperationCompleted, userState);
        }
        
        private void OnCrearNivelOperationCompleted(object arg) {
            if ((this.CrearNivelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearNivelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearLocal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearLocal(string nombre, string descripcion, string tipo) {
            this.Invoke("CrearLocal", new object[] {
                        nombre,
                        descripcion,
                        tipo});
        }
        
        /// <remarks/>
        public void CrearLocalAsync(string nombre, string descripcion, string tipo) {
            this.CrearLocalAsync(nombre, descripcion, tipo, null);
        }
        
        /// <remarks/>
        public void CrearLocalAsync(string nombre, string descripcion, string tipo, object userState) {
            if ((this.CrearLocalOperationCompleted == null)) {
                this.CrearLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearLocalOperationCompleted);
            }
            this.InvokeAsync("CrearLocal", new object[] {
                        nombre,
                        descripcion,
                        tipo}, this.CrearLocalOperationCompleted, userState);
        }
        
        private void OnCrearLocalOperationCompleted(object arg) {
            if ((this.CrearLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearLocalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearTipoLocal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearTipoLocal(string tipo) {
            this.Invoke("CrearTipoLocal", new object[] {
                        tipo});
        }
        
        /// <remarks/>
        public void CrearTipoLocalAsync(string tipo) {
            this.CrearTipoLocalAsync(tipo, null);
        }
        
        /// <remarks/>
        public void CrearTipoLocalAsync(string tipo, object userState) {
            if ((this.CrearTipoLocalOperationCompleted == null)) {
                this.CrearTipoLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearTipoLocalOperationCompleted);
            }
            this.InvokeAsync("CrearTipoLocal", new object[] {
                        tipo}, this.CrearTipoLocalOperationCompleted, userState);
        }
        
        private void OnCrearTipoLocalOperationCompleted(object arg) {
            if ((this.CrearTipoLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearTipoLocalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CrearUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CrearEdificioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CrearNivelCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CrearLocalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CrearTipoLocalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591