//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("directorioModel", "FK_LOCALES_0", "LOCAL_TIPOS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DirectorioInteractivoLogic.TIPO_LOCAL), "LOCALES", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DirectorioInteractivoLogic.LOCAL))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("directorioModel", "EDIFICIO_NIVELES", "EDIFICIOS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DirectorioInteractivoLogic.EDIFICIO), "NIVELES", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DirectorioInteractivoLogic.NIVEL))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("directorioModel", "NIVEL_LOCALES", "NIVELES", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DirectorioInteractivoLogic.NIVEL), "LOCALES", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DirectorioInteractivoLogic.LOCAL))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("directorioModel", "USUARIO_EDIFICIO", "EDIFICIOS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DirectorioInteractivoLogic.EDIFICIO), "USUARIOS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DirectorioInteractivoLogic.USUARIO))]

// Original file name:
// Generation date: 3/16/2012 6:20:19 AM
namespace DirectorioInteractivoLogic
{
    
    /// <summary>
    /// There are no comments for directorioEntities in the schema.
    /// </summary>
    public partial class directorioEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new directorioEntities object using the connection string found in the 'directorioEntities' section of the application configuration file.
        /// </summary>
        public directorioEntities() : 
                base("name=directorioEntities", "directorioEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new directorioEntities object.
        /// </summary>
        public directorioEntities(string connectionString) : 
                base(connectionString, "directorioEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new directorioEntities object.
        /// </summary>
        public directorioEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "directorioEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for EDIFICIOS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<EDIFICIO> EDIFICIOS
        {
            get
            {
                if ((this._EDIFICIOS == null))
                {
                    this._EDIFICIOS = base.CreateQuery<EDIFICIO>("[EDIFICIOS]");
                }
                return this._EDIFICIOS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<EDIFICIO> _EDIFICIOS;
        /// <summary>
        /// There are no comments for TIPO_LOCAL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<TIPO_LOCAL> TIPO_LOCAL
        {
            get
            {
                if ((this._TIPO_LOCAL == null))
                {
                    this._TIPO_LOCAL = base.CreateQuery<TIPO_LOCAL>("[TIPO_LOCAL]");
                }
                return this._TIPO_LOCAL;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<TIPO_LOCAL> _TIPO_LOCAL;
        /// <summary>
        /// There are no comments for LOCALES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<LOCAL> LOCALES
        {
            get
            {
                if ((this._LOCALES == null))
                {
                    this._LOCALES = base.CreateQuery<LOCAL>("[LOCALES]");
                }
                return this._LOCALES;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<LOCAL> _LOCALES;
        /// <summary>
        /// There are no comments for NIVELES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<NIVEL> NIVELES
        {
            get
            {
                if ((this._NIVELES == null))
                {
                    this._NIVELES = base.CreateQuery<NIVEL>("[NIVELES]");
                }
                return this._NIVELES;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<NIVEL> _NIVELES;
        /// <summary>
        /// There are no comments for USUARIOS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<USUARIO> USUARIOS
        {
            get
            {
                if ((this._USUARIOS == null))
                {
                    this._USUARIOS = base.CreateQuery<USUARIO>("[USUARIOS]");
                }
                return this._USUARIOS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<USUARIO> _USUARIOS;
        /// <summary>
        /// There are no comments for EDIFICIOS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToEDIFICIOS(EDIFICIO eDIFICIO)
        {
            base.AddObject("EDIFICIOS", eDIFICIO);
        }
        /// <summary>
        /// There are no comments for TIPO_LOCAL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTIPO_LOCAL(TIPO_LOCAL tIPO_LOCAL)
        {
            base.AddObject("TIPO_LOCAL", tIPO_LOCAL);
        }
        /// <summary>
        /// There are no comments for LOCALES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToLOCALES(LOCAL lOCAL)
        {
            base.AddObject("LOCALES", lOCAL);
        }
        /// <summary>
        /// There are no comments for NIVELES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToNIVELES(NIVEL nIVEL)
        {
            base.AddObject("NIVELES", nIVEL);
        }
        /// <summary>
        /// There are no comments for USUARIOS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUSUARIOS(USUARIO uSUARIO)
        {
            base.AddObject("USUARIOS", uSUARIO);
        }
    }
    /// <summary>
    /// There are no comments for directorioModel.EDIFICIO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO_EDIFICIO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="directorioModel", Name="EDIFICIO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EDIFICIO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EDIFICIO object.
        /// </summary>
        /// <param name="cODIGO_EDIFICIO">Initial value of CODIGO_EDIFICIO.</param>
        /// <param name="nOMBRE">Initial value of NOMBRE.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static EDIFICIO CreateEDIFICIO(long cODIGO_EDIFICIO, string nOMBRE)
        {
            EDIFICIO eDIFICIO = new EDIFICIO();
            eDIFICIO.CODIGO_EDIFICIO = cODIGO_EDIFICIO;
            eDIFICIO.NOMBRE = nOMBRE;
            return eDIFICIO;
        }
        /// <summary>
        /// There are no comments for property CODIGO_EDIFICIO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long CODIGO_EDIFICIO
        {
            get
            {
                return this._CODIGO_EDIFICIO;
            }
            set
            {
                this.OnCODIGO_EDIFICIOChanging(value);
                this.ReportPropertyChanging("CODIGO_EDIFICIO");
                this._CODIGO_EDIFICIO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO_EDIFICIO");
                this.OnCODIGO_EDIFICIOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _CODIGO_EDIFICIO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_EDIFICIOChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_EDIFICIOChanged();
        /// <summary>
        /// There are no comments for property NOMBRE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NOMBRE
        {
            get
            {
                return this._NOMBRE;
            }
            set
            {
                this.OnNOMBREChanging(value);
                this.ReportPropertyChanging("NOMBRE");
                this._NOMBRE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NOMBRE");
                this.OnNOMBREChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NOMBRE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBREChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBREChanged();
        /// <summary>
        /// There are no comments for property DESCRIPCION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DESCRIPCION
        {
            get
            {
                return this._DESCRIPCION;
            }
            set
            {
                this.OnDESCRIPCIONChanging(value);
                this.ReportPropertyChanging("DESCRIPCION");
                this._DESCRIPCION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPCION");
                this.OnDESCRIPCIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DESCRIPCION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanged();
        /// <summary>
        /// There are no comments for NIVELES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "EDIFICIO_NIVELES", "NIVELES")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<NIVEL> NIVELES
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<NIVEL>("directorioModel.EDIFICIO_NIVELES", "NIVELES");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<NIVEL>("directorioModel.EDIFICIO_NIVELES", "NIVELES", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for USUARIO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "USUARIO_EDIFICIO", "USUARIOS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public USUARIO USUARIO
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<USUARIO>("directorioModel.USUARIO_EDIFICIO", "USUARIOS").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<USUARIO>("directorioModel.USUARIO_EDIFICIO", "USUARIOS").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for USUARIO in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<USUARIO> USUARIOReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<USUARIO>("directorioModel.USUARIO_EDIFICIO", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<USUARIO>("directorioModel.USUARIO_EDIFICIO", "USUARIOS", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for directorioModel.TIPO_LOCAL in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TIPO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="directorioModel", Name="TIPO_LOCAL")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TIPO_LOCAL : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TIPO_LOCAL object.
        /// </summary>
        /// <param name="tIPO">Initial value of TIPO.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static TIPO_LOCAL CreateTIPO_LOCAL(string tIPO)
        {
            TIPO_LOCAL tIPO_LOCAL = new TIPO_LOCAL();
            tIPO_LOCAL.TIPO = tIPO;
            return tIPO_LOCAL;
        }
        /// <summary>
        /// There are no comments for property TIPO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TIPO
        {
            get
            {
                return this._TIPO;
            }
            set
            {
                this.OnTIPOChanging(value);
                this.ReportPropertyChanging("TIPO");
                this._TIPO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TIPO");
                this.OnTIPOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TIPO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTIPOChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTIPOChanged();
        /// <summary>
        /// There are no comments for LOCALES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "FK_LOCALES_0", "LOCALES")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<LOCAL> LOCALES
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LOCAL>("directorioModel.FK_LOCALES_0", "LOCALES");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<LOCAL>("directorioModel.FK_LOCALES_0", "LOCALES", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for directorioModel.LOCAL in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO_LOCAL
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="directorioModel", Name="LOCAL")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LOCAL : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LOCAL object.
        /// </summary>
        /// <param name="cODIGO_LOCAL">Initial value of CODIGO_LOCAL.</param>
        /// <param name="nOMBRE">Initial value of NOMBRE.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static LOCAL CreateLOCAL(int cODIGO_LOCAL, string nOMBRE)
        {
            LOCAL lOCAL = new LOCAL();
            lOCAL.CODIGO_LOCAL = cODIGO_LOCAL;
            lOCAL.NOMBRE = nOMBRE;
            return lOCAL;
        }
        /// <summary>
        /// There are no comments for property CODIGO_LOCAL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO_LOCAL
        {
            get
            {
                return this._CODIGO_LOCAL;
            }
            set
            {
                this.OnCODIGO_LOCALChanging(value);
                this.ReportPropertyChanging("CODIGO_LOCAL");
                this._CODIGO_LOCAL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO_LOCAL");
                this.OnCODIGO_LOCALChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO_LOCAL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_LOCALChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_LOCALChanged();
        /// <summary>
        /// There are no comments for property NOMBRE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NOMBRE
        {
            get
            {
                return this._NOMBRE;
            }
            set
            {
                this.OnNOMBREChanging(value);
                this.ReportPropertyChanging("NOMBRE");
                this._NOMBRE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NOMBRE");
                this.OnNOMBREChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NOMBRE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBREChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBREChanged();
        /// <summary>
        /// There are no comments for property DESCRIPCION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DESCRIPCION
        {
            get
            {
                return this._DESCRIPCION;
            }
            set
            {
                this.OnDESCRIPCIONChanging(value);
                this.ReportPropertyChanging("DESCRIPCION");
                this._DESCRIPCION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPCION");
                this.OnDESCRIPCIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DESCRIPCION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanged();
        /// <summary>
        /// There are no comments for LOCAL_TIPOS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "FK_LOCALES_0", "LOCAL_TIPOS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TIPO_LOCAL LOCAL_TIPOS
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TIPO_LOCAL>("directorioModel.FK_LOCALES_0", "LOCAL_TIPOS").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TIPO_LOCAL>("directorioModel.FK_LOCALES_0", "LOCAL_TIPOS").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for LOCAL_TIPOS in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TIPO_LOCAL> LOCAL_TIPOSReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TIPO_LOCAL>("directorioModel.FK_LOCALES_0", "LOCAL_TIPOS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TIPO_LOCAL>("directorioModel.FK_LOCALES_0", "LOCAL_TIPOS", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for NIVELE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "NIVEL_LOCALES", "NIVELES")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public NIVEL NIVELE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NIVEL>("directorioModel.NIVEL_LOCALES", "NIVELES").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NIVEL>("directorioModel.NIVEL_LOCALES", "NIVELES").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for NIVELE in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<NIVEL> NIVELEReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NIVEL>("directorioModel.NIVEL_LOCALES", "NIVELES");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<NIVEL>("directorioModel.NIVEL_LOCALES", "NIVELES", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for directorioModel.NIVEL in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO_NIVEL
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="directorioModel", Name="NIVEL")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NIVEL : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NIVEL object.
        /// </summary>
        /// <param name="cODIGO_NIVEL">Initial value of CODIGO_NIVEL.</param>
        /// <param name="nUMERO">Initial value of NUMERO.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static NIVEL CreateNIVEL(long cODIGO_NIVEL, long nUMERO)
        {
            NIVEL nIVEL = new NIVEL();
            nIVEL.CODIGO_NIVEL = cODIGO_NIVEL;
            nIVEL.NUMERO = nUMERO;
            return nIVEL;
        }
        /// <summary>
        /// There are no comments for property CODIGO_NIVEL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long CODIGO_NIVEL
        {
            get
            {
                return this._CODIGO_NIVEL;
            }
            set
            {
                this.OnCODIGO_NIVELChanging(value);
                this.ReportPropertyChanging("CODIGO_NIVEL");
                this._CODIGO_NIVEL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO_NIVEL");
                this.OnCODIGO_NIVELChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _CODIGO_NIVEL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_NIVELChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_NIVELChanged();
        /// <summary>
        /// There are no comments for property NUMERO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long NUMERO
        {
            get
            {
                return this._NUMERO;
            }
            set
            {
                this.OnNUMEROChanging(value);
                this.ReportPropertyChanging("NUMERO");
                this._NUMERO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NUMERO");
                this.OnNUMEROChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _NUMERO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNUMEROChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNUMEROChanged();
        /// <summary>
        /// There are no comments for property DESCRIPCION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DESCRIPCION
        {
            get
            {
                return this._DESCRIPCION;
            }
            set
            {
                this.OnDESCRIPCIONChanging(value);
                this.ReportPropertyChanging("DESCRIPCION");
                this._DESCRIPCION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPCION");
                this.OnDESCRIPCIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DESCRIPCION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanged();
        /// <summary>
        /// There are no comments for EDIFICIO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "EDIFICIO_NIVELES", "EDIFICIOS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EDIFICIO EDIFICIO
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EDIFICIO>("directorioModel.EDIFICIO_NIVELES", "EDIFICIOS").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EDIFICIO>("directorioModel.EDIFICIO_NIVELES", "EDIFICIOS").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for EDIFICIO in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EDIFICIO> EDIFICIOReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EDIFICIO>("directorioModel.EDIFICIO_NIVELES", "EDIFICIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EDIFICIO>("directorioModel.EDIFICIO_NIVELES", "EDIFICIOS", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for LOCALES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "NIVEL_LOCALES", "LOCALES")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<LOCAL> LOCALES
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LOCAL>("directorioModel.NIVEL_LOCALES", "LOCALES");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<LOCAL>("directorioModel.NIVEL_LOCALES", "LOCALES", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for directorioModel.USUARIO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NOMBRE_USUARIO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="directorioModel", Name="USUARIO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class USUARIO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new USUARIO object.
        /// </summary>
        /// <param name="nOMBRE_USUARIO">Initial value of NOMBRE_USUARIO.</param>
        /// <param name="pRIMER_NOMBRE">Initial value of PRIMER_NOMBRE.</param>
        /// <param name="sEGUNDO_NOMBRE">Initial value of SEGUNDO_NOMBRE.</param>
        /// <param name="pRIMER_APELLIDO">Initial value of PRIMER_APELLIDO.</param>
        /// <param name="sEGUNDO_APELLIDO">Initial value of SEGUNDO_APELLIDO.</param>
        /// <param name="eMAIL">Initial value of EMAIL.</param>
        /// <param name="pASSWORD">Initial value of PASSWORD.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static USUARIO CreateUSUARIO(string nOMBRE_USUARIO, string pRIMER_NOMBRE, string sEGUNDO_NOMBRE, string pRIMER_APELLIDO, string sEGUNDO_APELLIDO, string eMAIL, string pASSWORD)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.NOMBRE_USUARIO = nOMBRE_USUARIO;
            uSUARIO.PRIMER_NOMBRE = pRIMER_NOMBRE;
            uSUARIO.SEGUNDO_NOMBRE = sEGUNDO_NOMBRE;
            uSUARIO.PRIMER_APELLIDO = pRIMER_APELLIDO;
            uSUARIO.SEGUNDO_APELLIDO = sEGUNDO_APELLIDO;
            uSUARIO.EMAIL = eMAIL;
            uSUARIO.PASSWORD = pASSWORD;
            return uSUARIO;
        }
        /// <summary>
        /// There are no comments for property NOMBRE_USUARIO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NOMBRE_USUARIO
        {
            get
            {
                return this._NOMBRE_USUARIO;
            }
            set
            {
                this.OnNOMBRE_USUARIOChanging(value);
                this.ReportPropertyChanging("NOMBRE_USUARIO");
                this._NOMBRE_USUARIO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NOMBRE_USUARIO");
                this.OnNOMBRE_USUARIOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NOMBRE_USUARIO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBRE_USUARIOChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBRE_USUARIOChanged();
        /// <summary>
        /// There are no comments for property PRIMER_NOMBRE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PRIMER_NOMBRE
        {
            get
            {
                return this._PRIMER_NOMBRE;
            }
            set
            {
                this.OnPRIMER_NOMBREChanging(value);
                this.ReportPropertyChanging("PRIMER_NOMBRE");
                this._PRIMER_NOMBRE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PRIMER_NOMBRE");
                this.OnPRIMER_NOMBREChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PRIMER_NOMBRE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPRIMER_NOMBREChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPRIMER_NOMBREChanged();
        /// <summary>
        /// There are no comments for property SEGUNDO_NOMBRE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string SEGUNDO_NOMBRE
        {
            get
            {
                return this._SEGUNDO_NOMBRE;
            }
            set
            {
                this.OnSEGUNDO_NOMBREChanging(value);
                this.ReportPropertyChanging("SEGUNDO_NOMBRE");
                this._SEGUNDO_NOMBRE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SEGUNDO_NOMBRE");
                this.OnSEGUNDO_NOMBREChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _SEGUNDO_NOMBRE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSEGUNDO_NOMBREChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSEGUNDO_NOMBREChanged();
        /// <summary>
        /// There are no comments for property PRIMER_APELLIDO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PRIMER_APELLIDO
        {
            get
            {
                return this._PRIMER_APELLIDO;
            }
            set
            {
                this.OnPRIMER_APELLIDOChanging(value);
                this.ReportPropertyChanging("PRIMER_APELLIDO");
                this._PRIMER_APELLIDO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PRIMER_APELLIDO");
                this.OnPRIMER_APELLIDOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PRIMER_APELLIDO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPRIMER_APELLIDOChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPRIMER_APELLIDOChanged();
        /// <summary>
        /// There are no comments for property SEGUNDO_APELLIDO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string SEGUNDO_APELLIDO
        {
            get
            {
                return this._SEGUNDO_APELLIDO;
            }
            set
            {
                this.OnSEGUNDO_APELLIDOChanging(value);
                this.ReportPropertyChanging("SEGUNDO_APELLIDO");
                this._SEGUNDO_APELLIDO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SEGUNDO_APELLIDO");
                this.OnSEGUNDO_APELLIDOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _SEGUNDO_APELLIDO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSEGUNDO_APELLIDOChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSEGUNDO_APELLIDOChanged();
        /// <summary>
        /// There are no comments for property EMAIL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMAIL
        {
            get
            {
                return this._EMAIL;
            }
            set
            {
                this.OnEMAILChanging(value);
                this.ReportPropertyChanging("EMAIL");
                this._EMAIL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMAIL");
                this.OnEMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMAIL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMAILChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMAILChanged();
        /// <summary>
        /// There are no comments for property PASSWORD in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PASSWORD
        {
            get
            {
                return this._PASSWORD;
            }
            set
            {
                this.OnPASSWORDChanging(value);
                this.ReportPropertyChanging("PASSWORD");
                this._PASSWORD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PASSWORD");
                this.OnPASSWORDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PASSWORD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPASSWORDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPASSWORDChanged();
        /// <summary>
        /// There are no comments for EDIFICIOS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("directorioModel", "USUARIO_EDIFICIO", "EDIFICIOS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<EDIFICIO> EDIFICIOS
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EDIFICIO>("directorioModel.USUARIO_EDIFICIO", "EDIFICIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EDIFICIO>("directorioModel.USUARIO_EDIFICIO", "EDIFICIOS", value);
                }
            }
        }
    }
}
